blank_issues_enabled: true
contact_links:
  - name: Pinax Documentation
    url: https://pinaxproject.com/pinax/
    about: Comprehensive Pinax docs
  - name: Pinax Community Health File Repo
    url: https://github.com/pinax/.github
    about: Pinax default community health files
  - name: Pinax Slack
    url: http://slack.pinaxproject.com/
    about: Pinax support channel
