blank_issues_enabled: true
contact_links:
  - name: Pinax Documentation
    url: https://pinaxproject.com/pinax/
    about: Comprehensive documentation
  - name: Pinax Community Health File Repo
    url: https://github.com/pinax/.github
    about: Default community health files
  - name: Pinax Wiki
    url: https://github.com/pinax/pinax/wiki
    about: Current and historical release notes
  - name: Pinax Slack
    url: http://slack.pinaxproject.com/
    about: Support channel
